SectorMap Class Reference
MAD-like Sectormap objects.
#include <SectorMap.h>
Public Member Functions
SectorMap ()
construct empty map
SectorMap (const SectorMap &S)
copy constructor
SectorMap (double sigx, double sigy, double R, double length, double gamma0)
construct a simple continuous focusing element
SectorMap & operator= (const SectorMap &M)
SectorMap operator * (const SectorMap &M)
multiply two maps
string & get_name ()
get or set element name
double & get_L ()
get or set element length
double & get_K (int j)
double & get_T (int j, int i)
get or set matrix elements
TwissP & get_twiss ()
double get_betx ()
double get_bety ()
SectorMap * get_map ()
return pointer to sectormap
void phase_advance (double &sigx, double &sigy)
calculates phase advances per element
void transport (vektor &R1, vektor &R0)
transport particle coordinates through the sector
Detailed Description
MAD-like Sectormap objects.
Definition at line 11 of file SectorMap.h.
Constructor & Destructor Documentation
SectorMap::SectorMap (double sigx, double sigy, double R, double length, double gamma0)
construct a simple continuous focusing element
Generates a linear transport map for a simple continous focusing element of length=length, bending radius R and phase advances [grad] sigma_x and sigma_y
Definition at line 20 of file SectorMap.cpp.
References TwissP::alpx, TwissP::alpy, TwissP::betx, TwissP::bety, TwissP::Dx, and get_T().
21 {
22  ElementName="CF";
23  L=length;
24  double beta0=sqrt((gamma0*gamma0-1.0)/(gamma0*gamma0));
25  double eta0=pow(R*sigx/length,2)-1.0/pow(gamma0,2);
26  for(int j=0; j<36; j++) T[j]=0.0; 
27  for(int j=0; j<6; j++)  K[j]=0.0; 
28  get_T(0,0)=cos(sigx);
29  get_T(0,1)=length/sigx*sin(sigx);
30  if (R>0.0)
31   get_T(0,5)=length*length/(sigx*sigx*R)*(1.0-cos(sigx))/beta0;
32  else
33   get_T(0,5)=0.0; 
34  get_T(1,0)=-sigx/length*sin(sigx);
35  get_T(1,1)=cos(sigx);
36  if (R>0.0)
37   get_T(1,5)=length/(sigx*R)*sin(sigx)/beta0;
38  else
39   get_T(1,5)=0.0;
40  get_T(2,2)=cos(sigy);
41  get_T(2,3)=length/sigy*sin(sigy);
42  get_T(3,2)=-sigy/length*sin(sigy);
43  get_T(3,3)=cos(sigy);
44  get_T(4,4)=1.0;
45  get_T(4,5)=-eta0*length/(beta0*beta0);
46  get_T(5,5)=1.0;
47  twiss.betx=length/sigx;
48  twiss.bety=length/sigy;
49  twiss.alpx=0.0;
50  twiss.alpy=0.0;
51  if( R > 0.0)
52   twiss.Dx=pow(length/sigx,2)/R;
53  else
54   twiss.Dx=0.0; 
55 }
Member Function Documentation
void SectorMap::phase_advance (double & sigx, double & sigy)
calculates phase advances per element
Calculates the phase advances per element.
Definition at line 107 of file SectorMap.cpp.
References get_T().
108 {
109  double ah=get_T(0,0);
110  double dh=get_T(1,1); 
111  double av=get_T(2,2);  
112  double dv=get_T(3,3);
113  sigx=acos(0.5*(ah+dh));
114  sigy=acos(0.5*(av+dv));
115 }
void SectorMap::transport (vektor & R1, vektor & R0)
transport particle coordinates through the sector
Detailed description
Definition at line 91 of file SectorMap.cpp.
Referenced by Pic::transport().
92 {
93  for(int j=0;j<6;j++)
94    {
95     R1[j]=0.0;
96     for(int l=0;l<6;l++)
97      R1[j]+=T[j*6+l]*R0[l];             
98    }
99 }
The documentation for this class was generated from the following files:
SectorMap.h
SectorMap.cpp